// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_LowercaseIdentifier = {__proto__:null,assert:38, case:40, const:42, external:44, fn:46, if:48, import:50, type:52, let:54, panic:56, pub:58, todo:60, use:62}
export const parser = LRParser.deserialize({
  version: 13,
  states: "!jO!kOPOOOOOO'#C_'#C_O!rOQO'#CeOOOO'#Cl'#ClOOOO'#Ci'#CiO!zOPO'#CkQOOOOOOOOO'#Cg'#CgOOOO,59P,59PO#ROPO,59POOOO-E6g-E6gOOOO1G.k1G.k",
  stateData: "#c~OQSOSPOTPOUPOVPOWPOYSO[SOaQOcVOdVOeVOfVOgVOhVOiVOjVOkVOlVOmVOnVOoVOpSO~O^_P~PQOaWObXO~O^_X~PQOaZO~OWTUVSYQ[pS~",
  goto: "saPPPbPPPPPbPfPjPpfTROTTSOTQTORYTRUO",
  nodeNames: "⚠ Program Comment Number Decimal Hex Octal Binary Float String UppercaseIdentifier Keyword LowercaseIdentifier",
  maxTerm: 32,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "9a~RaOr!Wrs#]s}!W}!O#d!O!P!W!P!Q.m!Q!R0t!R![2c![!c!W!c!}3[!}#O!W#O#P4z#P#R!W#R#S5]#S#T!W#T#o8b#o~!WR!_SbQpPOr!ks#O!k#O#P!|#P~!kQ!pSbQOr!ks#O!k#O#P!|#P~!kQ#PSrs!k#b#c!k#f#g!k#h#i!k~#dOa~pPR#kXbQpPOr!ks!Q!k!Q!R$W!R![(m![#O!k#O#P!|#P#R!k#R#S-x#S~!kR$_fbQSPOr!ks!O!k!O!P%s!P!Q!k!Q![(m![!d!k!d!e)d!e!q!k!q!r*r!r!z!k!z!{,Q!{#O!k#O#P!|#P#R!k#R#S(m#S#U!k#U#V)d#V#c!k#c#d*r#d#l!k#l#m,Q#m~!kR%zYbQWPOr!ks!Q!k!Q![%s![#O!k#O#P!|#P#R!k#R#S%s#S#X!k#X#Y&j#Y~!kR&oYbQOr!ks}!k}!O'_!O!Q!k!Q!['|![#O!k#O#P!|#P#R!k#R#S'|#S~!kR'dWbQOr!ks!Q!k!Q!['|![#O!k#O#P!|#P#R!k#R#S'|#S~!kR(TWbQWPOr!ks!Q!k!Q!['|![#O!k#O#P!|#P#R!k#R#S'|#S~!kR(tYbQSPOr!ks!O!k!O!P%s!P!Q!k!Q![(m![#O!k#O#P!|#P#R!k#R#S(m#S~!kR)iWbQOr!ks!Q!k!Q!S*R!S#O!k#O#P!|#P#R!k#R#S*R#S~!kR*YWbQVPOr!ks!Q!k!Q!S*R!S#O!k#O#P!|#P#R!k#R#S*R#S~!kR*wWbQOr!ks!Q!k!Q!Y+a!Y#O!k#O#P!|#P#R!k#R#S+a#S~!kR+hWbQUPOr!ks!Q!k!Q!Y+a!Y#O!k#O#P!|#P#R!k#R#S+a#S~!kR,V[bQOr!ks!Q!k!Q![,{![!c!k!c!i,{!i#O!k#O#P!|#P#R!k#R#S,{#S#T!k#T#Z,{#Z~!kR-S[bQTPOr!ks!Q!k!Q![,{![!c!k!c!i,{!i#O!k#O#P!|#P#R!k#R#S,{#S#T!k#T#Z,{#Z~!kR-}YbQOr!ks!O!k!O!P%s!P!Q!k!Q![-x![#O!k#O#P!|#P#R!k#R#S-x#S~!kR.tUbQpPOr!ks!P!k!P!Q/W!Q#O!k#O#P!|#P~!kR/_VbQQPOY/WYZ!kZr/Wrs/ts#O/W#O#P0P#P~/WP/yQQPOY/tZ~/tR0UYQPOY/tZr/trs/Ws#b/t#b#c/W#c#f/t#f#g/W#g#h/t#h#i/W#i~/tR0}fbQSPpPOr!ks!O!k!O!P%s!P!Q!k!Q![(m![!d!k!d!e)d!e!q!k!q!r*r!r!z!k!z!{,Q!{#O!k#O#P!|#P#R!k#R#S(m#S#U!k#U#V)d#V#c!k#c#d*r#d#l!k#l#m,Q#m~!kR2lYbQSPpPOr!ks!O!k!O!P%s!P!Q!k!Q![(m![#O!k#O#P!|#P#R!k#R#S(m#S~!kR3eYbQYPpPOr!ks!Q!k!Q![4T![!c!k!c!}4T!}#O!k#O#P!|#P#T!k#T#o4T#o~!kR4[YbQYPOr!ks!Q!k!Q![4T![!c!k!c!}4T!}#O!k#O#P!|#P#T!k#T#o4T#o~!kR5PSpPrs!k#b#c!k#f#g!k#h#i!kR5f^bQ[PpPOr!ks!O!k!O!P%s!P!Q!k!Q![6b![!c!k!c!}7e!}#O!k#O#P!|#P#R!k#R#S6b#S#T!k#T#o7e#o~!kR6i^bQ[POr!ks!O!k!O!P%s!P!Q!k!Q![6b![!c!k!c!}7e!}#O!k#O#P!|#P#R!k#R#S6b#S#T!k#T#o7e#o~!kR7l[bQ[POr!ks!Q!k!Q![7e![!c!k!c!}7e!}#O!k#O#P!|#P#R!k#R#S7e#S#T!k#T#o7e#o~!kR8k[bQ[PpPOr!ks!Q!k!Q![7e![!c!k!c!}7e!}#O!k#O#P!|#P#R!k#R#S7e#S#T!k#T#o7e#o~!k",
  tokenizers: [0, 1],
  topRules: {"Program":[0,1]},
  specialized: [{term: 12, get: value => spec_LowercaseIdentifier[value] || -1}],
  tokenPrec: 100
})
