// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Program = 2,
  Number = 3,
  Decimal = 4,
  Hex = 5,
  Octal = 6,
  Binary = 7,
  Float = 8,
  String = 9,
  UppercaseName = 10,
  Keyword = 11
